### PR TITLE
add sparse search

### PR DESCRIPTION
**Pull request by amiremohamadi**

### CODE REVIEW

**Comment by agourlay** [comment]
Thanks for your interest in crasher :+1: 

With your PR, users can only test one type of vector at a time..

However, crasher always creates several named vectors with different configurations on purpose.

The goal being that crasher should test by default the largest surface of features.

I would prefer if we could instead use batch search to test all those vectors by default.

WDYT?

**Comment by amiremohamadi** [comment]
@agourlay thanks for the review. i modified my patch in order to have a batch search on sparse/dense vectors at the same time. could you please take another look at it?

**Comment by agourlay** [comment]
Sorry for the delay and conflicts!

I am currently moving fast on this project so it creates some noise.

Regarding your PR, what I meant was to use search batch as in https://qdrant.tech/documentation/concepts/search/?q=search+ba#batch-search-api

That is submitting one search query per named vector at once.

**Comment by agourlay** [comment]
FYI I am currently performing a large refactoring to handle more vector configurations and I will most likely have to handle the aforementioned batch search as well.

Please do not spend time on this :)

**Comment by agourlay** [comment]
Done in https://github.com/qdrant/crasher/commit/1fb5ca95e4b206a42339a05afcfff714d201bbad

Crasher might be too unstable/experimental to receive meaningful contributions for the moment.
Sorry for your experience on this PR!

**Pull request closed without merging**
